### ISSUE TITLE
pcdm doesn't see xfce session on pure freebsd

### ISSUE THREAD

**Issue by angelescuo** [pcbsd/pcbsd#89]
Hi,
My name is Angelescu Ovidiu .
I have compiled and installed pcdm in pure freebsd and noticed that pcdm it doesn't read as it should 
xfce.desktop from /usr/local/share/xsessions. Of course the result is that no XFCE session is shown in greeter.
Using gdm instead of pcdm all it's ok ( xfce session is listed).
It seems that when parsing /usr/local/share/xsessions/xfce.desktop from pure freebsd pcdm fails somehow. Using 03xfce.desktop from pcbsd all it's ok.
Thank you.

**Comment by kmoore134** [comment]
I wonder what is different in the particular .desktop file for XFCE? Ken, can you take a look at this? Angelescu, can you provide the broken xfce.desktop for us to look at?

**Comment by beanpole135** [comment]
I am looking at it now, and it appears that the xfce.desktop file does not provide the "TryExec=<something>" line for binary installation verification. PCDM treats files that are missing that definition as mal-formed and invalid, which is why it is ignoring it.

I just put a quick fallback routine into PCDM where if there is no "TryExec" explicitly defined, it will check for the existance of the first binary listed on the "Exec" line instead. In the meantime just add the following line to your current xfce.desktop file:

"TryExec=startxfce4"
